name: mark_it
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:

  geolocator: ^8.1.0
  great_circle_distance: ^1.0.1
  cloud_firestore: ^3.1.10
  firebase: ^9.0.2
  flutter_login: ^3.2.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

