name: mark_it
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:

  geolocator: ^8.1.0
  great_circle_distance: ^1.0.1
  cloud_firestore: ^3.1.10
  firebase: ^9.0.2
  flutter_login: ^3.2.0
  firebase_auth: ^3.3.11
  fluttermoji: ^1.0.0
  camera: ^0.9.4+16
  image: ^3.1.3
  path_provider: ^2.0.9
  google_ml_kit: ^0.7.3
  image_picker: ^0.8.4+11
  tflite_flutter: ^0.9.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/mobilefacenet.tflite

